baseURL: 'https://www.otifik.xyz'
languageCode: zh-cn
title: otifik's blog
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 15
                # - name: WiKi
                #   url: https://github.com/adityatelange/hugo-PaperMod/wiki/
                # - name: Discord
                #   url: https://discord.gg/ahpmTvhVmp

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "otifik,blog"
    author: otifik
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    comments: true
    # images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: otifik
        imageUrl: "img/moka.png"
        imageTitle: 
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Tech
              url: posts/tech
            - name: Other
              url: posts/other

    homeInfoParams:
        Title: "otifik的个人博客"
        Content: >
            一个喜欢打音游、画画的安卓开发者
    socialIcons:
        - name: github
          url: "https://github.com/otifik"
        - name: bilibili
          url: "https://space.bilibili.com/123965798"

    # editPost:
    #     URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
        favicon: "img/moka_circle.png"
        favicon16x16: "img/moka_circle.png"
        favicon32x32: "img/moka_circle.png"
        apple_touch_icon: "img/moka_circle.png"
        safari_pinned_tab: "img/moka_circle.png"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true